vlog -work work D:/altera/13.0sp1/ProjetoCircuitos/simulation/modelsim/Waveform.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.MaquinaSalgados_vlg_vec_tst
onerror {resume}
add wave {MaquinaSalgados_vlg_vec_tst/i1/cancelar}
add wave {MaquinaSalgados_vlg_vec_tst/i1/clock}
add wave {MaquinaSalgados_vlg_vec_tst/i1/confirma_moeda}
add wave {MaquinaSalgados_vlg_vec_tst/i1/confirma_salgado}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[9]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[8]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[7]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolucao[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/devolvido}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_centena[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_dezena[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_moeda_unidade[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/display_salgado[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estado}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estado[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estado[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estado[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado1}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado1[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado1[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado1[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado1[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado2}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado2[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado2[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado2[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado2[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado3}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado3[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado3[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado3[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado3[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado4}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado4[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado4[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado4[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado4[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado5}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado5[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado5[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado5[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/estoque_salgado5[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/inicia}
add wave {MaquinaSalgados_vlg_vec_tst/i1/moeda}
add wave {MaquinaSalgados_vlg_vec_tst/i1/moeda[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/moeda[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/moeda_nao_permitida}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[9]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[8]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[7]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/preco_salgado[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/reset}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_escolhido}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_escolhido[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_escolhido[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_escolhido[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_invalido}
add wave {MaquinaSalgados_vlg_vec_tst/i1/salgado_liberado}
add wave {MaquinaSalgados_vlg_vec_tst/i1/sem_estoque}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[9]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[8]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[7]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/troco[0]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[9]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[8]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[7]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[6]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[5]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[4]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[3]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[2]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[1]}
add wave {MaquinaSalgados_vlg_vec_tst/i1/valor_inserido[0]}
run -all
